server:
  port: 8087

spring:
  # 热部署静态文件
  thymeleaf:
    cache: false
  application:
    name: msa-weather-report-eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      feignName:
        # 连接超时时间
        connectTimeout: 5000
        # 读数据的超时时间
        readTimeout: 5000
  hystrix:
    enabled: true