server:
  port: 8081

spring:
  redis:
    host: localhost
    password: lt5227
    database: 5
  application:
    name: msa-weather-collection-eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
