spring:
  application:
    name: micro-weather-config-client-bus
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
