spring:
  application:
    name: micro-weahter-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lt5227/spring-cloud-microservices-development.git
          search-paths: config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka